/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "batchText": "batch output formats",
    "copyrightText": "©2011 John Einselen / Vectorform LLC",
    "dateReverseText": "date order",
    "dateSpacerText": "date",
    "dateSpacerText1": "date spacer",
    "dateText": "date",
    "done": "done",
    "done1": "done",
    "download": "download",
    "drop": "drop media files here",
    "dropDetail": "high bitrate MP4 prefered",
    "fail": "file processing failed,\nplease try again",
    "feedback": "Quicktime ProRes422",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/alchemist",
    "location2Text": "ffmpeg",
    "location2Text1": "ffmpeg2theora",
    "locationText": "qt_tools",
    "locationText1": "ffmpeg",
    "nameFileText": "file sheet prefix",
    "nameSpriteText": "sprite sheet suffix",
    "nameText": "sprite sheet suffix",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "optionsText": "flip over for more options",
    "outputText": "output files",
    "sharpAmount": "amount",
    "sharpSettings": "unsharp\nmask\nsettings",
    "sharpSize": "size",
    "sharpThresh": "threshold",
    "skip": "skip version",
    "spacerText": "seperator",
    "spacerText1": "text spacer",
    "started": "file processing has started, initial setup underway",
    "startedDetails": "this may take a minute",
    "success": "file processing successful, busy encoding media",
    "successDetails": "may take a few minutes or longer, depending on video length",
    "wrong": "wrong file format\nplease try again"
};











