/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "batchText": { "text": "batchText", "view": "DC.Text" },
    "dateReverseText": { "text": "dateReverseText", "view": "DC.Text" },
    "dateSpacerText": { "text": "dateSpacerText", "view": "DC.Text" },
    "dateText": { "text": "feedback", "view": "DC.Text" },
    "doneSave": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showFront", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "download": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "versionDownload", "rightImageWidth": 5, "text": "download", "view": "DC.View" },
    "drop": { "text": "drop", "view": "DC.Text" },
    "failButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "failText": { "text": "fail", "view": "DC.Text" },
    "iaian7com": { "text": "iaian7com", "view": "DC.Text" },
    "image": { "view": "DC.ImageLayout" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack", "view": "DC.View" },
    "location2Text": { "text": "location2Text", "view": "DC.Text" },
    "locationText": { "text": "locationText", "view": "DC.Text" },
    "new": { "text": "new", "view": "DC.Text" },
    "newVersion": { "text": "newVersion", "view": "DC.Text" },
    "skip": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "skip", "view": "DC.View" },
    "spacerText": { "text": "spacerText", "view": "DC.Text" },
    "stack": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "startedButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done1", "view": "DC.View" },
    "startedDetails": { "text": "startedDetails", "view": "DC.Text" },
    "startedText": { "text": "started", "view": "DC.Text" },
    "successButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "successDetails": { "text": "successDetails", "view": "DC.Text" },
    "successText": { "text": "success", "view": "DC.Text" },
    "text": { "text": "copyrightText", "view": "DC.Text" },
    "type": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "name": "type", "onchange": "updateType", "options": [["ProRes422", "0"], ["HDV 1080p", "1"], ["HDV 720p", "2"], ["Apple Intermediate Codec", "3"], ["Batch output formats", "4"]], "rightImageWidth": 16, "view": "DC.View" },
    "wrongButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "wrongText": { "text": "wrong", "view": "DC.Text" }
};










